[package]
name = "aoc2016"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
hex-literal = "0.4.1"
hex-string = "0.1.0"
md-5 = "0.10.5"
